#!/bin/sh

sudo wget https://github.com/5jjCopter/navio/archive/master.zip

sudo unzip master.zip

sudo rm master.zip

sudo wget https://github.com/5jjCopter/tipos-instalacion/archive/master.zip

sudo unzip master.zip

sudo rm master.zip

cd navio-master

sudo chmod 775 interfaces

sudo chmod 775 actualizacion2.sh

sudo cp actualizacion2.sh /home/pi

cd /etc/network

sudo rm interfaces

cd

cd navio-master

sudo cp interfaces /etc/network

cd

cd tipos-instalacion-master
sudo chmod 775 permisos.sh
sudo chmod 775 copiar.sh
sudo ./permisos.sh
sudo ./copiar.sh
cd
sudo wget https://github.com/5jjCopter/instalar/archive/master.zip
sudo unzip master.zip
cd instalar-master
sudo chmod 775 Instalar-solo-video
sudo ./instalar-solo-video
cd
sudo rm master.zip
sudo rm -rf instalar-master
# QUITAR (#) DEL VEICULO QUE QUIERA INSTALAR

#sudo systemctl daemon-reload & sudo systemctl enable 
#sudo systemctl daemon-reload & sudo systemctl enable APMrover2
#sudo systemctl daemon-reload & sudo systemctl enable ArduCopter-heli	
#sudo systemctl daemon-reload & sudo systemctl enable ArduCopter-hexa
#sudo systemctl daemon-reload & sudo systemctl enable ArduCopter-octa
#sudo systemctl daemon-reload & sudo systemctl enable ArduCopter-octa-quad
sudo systemctl daemon-reload & sudo systemctl enable ArduCopter-quad
#sudo systemctl daemon-reload & sudo systemctl enable ArduCopter-tri
#sudo systemctl daemon-reload & sudo systemctl enable ArduCopter-y6	
#sudo systemctl daemon-reload & sudo systemctl enable ArduPlane
cd

sudo ./actualizacion2.sh

sudo reboot
