#!/bin/sh

sudo wget https://github.com/5jjCopter/navio/archive/master.zip

sudo unzip master.zip

cd navio-master

sudo chmod 775 interfaces

sudo cp ardupilot.service /lib/systemd/system

sudo cp video.service /lib/systemd/system

sudo cp ardupilot /home/pi

sudo cp video /home/pi

sudo cp temp.py /home/pi

sudo cp actualizacion2.sh /home/pi

sudo cp mavproxy.sh /home/pi

cd /etc/network

sudo rm interfaces

cd /home/pi/navio-master

sudo cp interfaces /etc/network

cd /home/pi

sudo chmod 775 ardupilot

sudo chmod 775 video

sudo chmod 775 temp.py

sudo chmod 775 actualizacion2.sh

sudo chmod 775 mavproxy.sh

sudo systemctl daemon-reload

sudo systemctl enable video

sudo systemctl daemon-reload

sudo systemctl enable ardupilot

sudo ./actualizacion2.sh

sudo ./mavproxy.sh

sudo reboot





