#!/bin/sh

sudo apt-get install apm-navio

sudo wget https://github.com/5jjCopter/navio/archive/master.zip

sudo unzip master.zip

cd navio-master

sudo cp ardupilot.service /lib/systemd/system

sudo cp video.service /lib/systemd/system

sudo cp ardupilot /home/pi

sudo cp video /home/pi

sudo cp actualizacion /home/pi

sudo cp temp.py /home/pi

cd /home/pi

sudo chmod 775 ardupilot

sudo chmod 775 video

sudo chmod 775 temp.py

sudo chmod 775 actualizacion

sudo systemctl daemon-reload

sudo systemctl enable video

sudo systemctl daemon-reload

sudo systemctl enable ardupilot

cd

sudo rm master.zip

sudo reboot

cd

