#!/bin/sh

sudo wget 'https://files.emlid.com/apm/apm-navio2_3.4-unstable.deb' -O apm-navio2.deb
sudo dpkg -i apm-navio2.deb

sudo wget https://github.com/5jjCopter/navio/archive/master.zip

sudo unzip master.zip

cd navio-master

sudo cp ardupilot.service /lib/systemd/system

sudo cp video.service /lib/systemd/system

sudo cp ardupilot /home/pi

sudo cp video /home/pi

sudo cp temp.py /home/pi

cd /home/pi

sudo chmod 775 ardupilot

sudo chmod 775 video

sudo chmod 775 actualizacion2

sudo chmod 775 temp.py

sudo systemctl daemon-reload

sudo systemctl enable video

sudo systemctl daemon-reload

sudo systemctl enable ardupilot

cd

sudo rm master.zip

cd

sudo ./actualizacion2

sudo reboot

cd
